---
- name: debug message
  hosts: localhost 
  tasks:
    - name: shell
      ansible.builtin.shell: |
        date
        uname -n
        id
      register: result_shell

    - name: debug msg
      ansible.builtin.debug:
        msg: "{{ result_shell.stdout_lines }}" 
