---
- name: debug message
  hosts: localhost 
  tasks:
    - name: Get event list
      uri:
        url: "https://randomuser.me/api" 
        headers:
          Content-Type: application/json
        status_code: 200
        method: GET
        return_content: yes
      register: result_get_events_list
    
    - name: debug
      debug:
        #var: result_get_events_list
        var: result_get_events_list.json
